[package]
name = "wpsy0/nope-framework"
description = "N.O.P.E. (No Organization, Pure Experiment)"
license = "MIT"
authors = ["David Bellerati"]
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml"]

[dependencies]
